---
spring:
  application:
    name: notes
  datasource:
    url:  jdbc:postgresql://postgres-service:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:d}
    password: ${POSTGRES_PASSWORD:d}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: /logs/application.log
  level:
    root: INFO