apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  type: NodePort
  selector:
    app: notes-image
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007